# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainView.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Info = QtWidgets.QWidget()
        self.Info.setObjectName("Info")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Info)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.Info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.numAnnoLab = QtWidgets.QLabel(self.frame_2)
        self.numAnnoLab.setObjectName("numAnnoLab")
        self.verticalLayout_2.addWidget(self.numAnnoLab)
        self.RegionConfigLab = QtWidgets.QLabel(self.frame_2)
        self.RegionConfigLab.setObjectName("RegionConfigLab")
        self.verticalLayout_2.addWidget(self.RegionConfigLab)
        self.DedupConfigLab = QtWidgets.QLabel(self.frame_2)
        self.DedupConfigLab.setObjectName("DedupConfigLab")
        self.verticalLayout_2.addWidget(self.DedupConfigLab)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.FlankingTabLab = QtWidgets.QLabel(self.frame_2)
        self.FlankingTabLab.setObjectName("FlankingTabLab")
        self.verticalLayout_2.addWidget(self.FlankingTabLab)
        self.UnmaskTabLab = QtWidgets.QLabel(self.frame_2)
        self.UnmaskTabLab.setObjectName("UnmaskTabLab")
        self.verticalLayout_2.addWidget(self.UnmaskTabLab)
        self.DedupTabLab = QtWidgets.QLabel(self.frame_2)
        self.DedupTabLab.setObjectName("DedupTabLab")
        self.verticalLayout_2.addWidget(self.DedupTabLab)
        self.CalcQualButton = QtWidgets.QPushButton(self.frame_2)
        self.CalcQualButton.setObjectName("CalcQualButton")
        self.verticalLayout_2.addWidget(self.CalcQualButton)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.OverlappingLab = QtWidgets.QLabel(self.frame_2)
        self.OverlappingLab.setObjectName("OverlappingLab")
        self.verticalLayout_2.addWidget(self.OverlappingLab)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.totalAnnoSenseLab = QtWidgets.QLabel(self.frame_2)
        self.totalAnnoSenseLab.setObjectName("totalAnnoSenseLab")
        self.verticalLayout_2.addWidget(self.totalAnnoSenseLab)
        self.totalAnnoAntiLab = QtWidgets.QLabel(self.frame_2)
        self.totalAnnoAntiLab.setObjectName("totalAnnoAntiLab")
        self.verticalLayout_2.addWidget(self.totalAnnoAntiLab)
        self.totalAnnoAbsentLab = QtWidgets.QLabel(self.frame_2)
        self.totalAnnoAbsentLab.setObjectName("totalAnnoAbsentLab")
        self.verticalLayout_2.addWidget(self.totalAnnoAbsentLab)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.Info)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3.addWidget(self.frame_3)
        self.tabWidget.addTab(self.Info, "")
        self.Inspect = QtWidgets.QWidget()
        self.Inspect.setObjectName("Inspect")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Inspect)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.Inspect)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.label_12 = QtWidgets.QLabel(self.Inspect)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.frame_4 = QtWidgets.QFrame(self.Inspect)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(9, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.idEntry = QtWidgets.QLineEdit(self.frame_4)
        self.idEntry.setObjectName("idEntry")
        self.horizontalLayout_2.addWidget(self.idEntry)
        self.annoButton = QtWidgets.QPushButton(self.frame_4)
        self.annoButton.setObjectName("annoButton")
        self.horizontalLayout_2.addWidget(self.annoButton)
        self.contigButton = QtWidgets.QPushButton(self.frame_4)
        self.contigButton.setObjectName("contigButton")
        self.horizontalLayout_2.addWidget(self.contigButton)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.tabWidget.addTab(self.Inspect, "")
        self.Analysis = QtWidgets.QWidget()
        self.Analysis.setObjectName("Analysis")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Analysis)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.Analysis)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame_7)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.GenomicRB = QtWidgets.QRadioButton(self.groupBox)
        self.GenomicRB.setChecked(True)
        self.GenomicRB.setObjectName("GenomicRB")
        self.verticalLayout_8.addWidget(self.GenomicRB)
        self.OriSenseRB = QtWidgets.QRadioButton(self.groupBox)
        self.OriSenseRB.setObjectName("OriSenseRB")
        self.verticalLayout_8.addWidget(self.OriSenseRB)
        self.OriAntiRB = QtWidgets.QRadioButton(self.groupBox)
        self.OriAntiRB.setObjectName("OriAntiRB")
        self.verticalLayout_8.addWidget(self.OriAntiRB)
        self.OriBiRB = QtWidgets.QRadioButton(self.groupBox)
        self.OriBiRB.setObjectName("OriBiRB")
        self.verticalLayout_8.addWidget(self.OriBiRB)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_7)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.EndSenseRB = QtWidgets.QRadioButton(self.groupBox_3)
        self.EndSenseRB.setObjectName("EndSenseRB")
        self.verticalLayout_10.addWidget(self.EndSenseRB)
        self.EndAntiRB = QtWidgets.QRadioButton(self.groupBox_3)
        self.EndAntiRB.setObjectName("EndAntiRB")
        self.verticalLayout_10.addWidget(self.EndAntiRB)
        self.EndBothRB = QtWidgets.QRadioButton(self.groupBox_3)
        self.EndBothRB.setChecked(True)
        self.EndBothRB.setObjectName("EndBothRB")
        self.verticalLayout_10.addWidget(self.EndBothRB)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_7)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.SizeAllRB = QtWidgets.QRadioButton(self.groupBox_2)
        self.SizeAllRB.setChecked(True)
        self.SizeAllRB.setObjectName("SizeAllRB")
        self.verticalLayout_9.addWidget(self.SizeAllRB)
        self.SizeLargestRB = QtWidgets.QRadioButton(self.groupBox_2)
        self.SizeLargestRB.setObjectName("SizeLargestRB")
        self.verticalLayout_9.addWidget(self.SizeLargestRB)
        self.SizeClosestRB = QtWidgets.QRadioButton(self.groupBox_2)
        self.SizeClosestRB.setObjectName("SizeClosestRB")
        self.verticalLayout_9.addWidget(self.SizeClosestRB)
        self.SizeFixedRB = QtWidgets.QRadioButton(self.groupBox_2)
        self.SizeFixedRB.setObjectName("SizeFixedRB")
        self.verticalLayout_9.addWidget(self.SizeFixedRB)
        self.FixedSizeEntry = QtWidgets.QLineEdit(self.groupBox_2)
        self.FixedSizeEntry.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FixedSizeEntry.sizePolicy().hasHeightForWidth())
        self.FixedSizeEntry.setSizePolicy(sizePolicy)
        self.FixedSizeEntry.setObjectName("FixedSizeEntry")
        self.verticalLayout_9.addWidget(self.FixedSizeEntry)
        self.SizeEqualBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.SizeEqualBox.setObjectName("SizeEqualBox")
        self.verticalLayout_9.addWidget(self.SizeEqualBox)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.line_2 = QtWidgets.QFrame(self.frame_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.frame_13 = QtWidgets.QFrame(self.frame_8)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.RecursiveBox = QtWidgets.QCheckBox(self.frame_13)
        self.RecursiveBox.setObjectName("RecursiveBox")
        self.horizontalLayout_8.addWidget(self.RecursiveBox)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.TransEntry = QtWidgets.QLineEdit(self.frame_10)
        self.TransEntry.setObjectName("TransEntry")
        self.horizontalLayout_5.addWidget(self.TransEntry)
        self.TransButton = QtWidgets.QPushButton(self.frame_10)
        self.TransButton.setObjectName("TransButton")
        self.horizontalLayout_5.addWidget(self.TransButton)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.label_10 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.AnalysisOutEntry = QtWidgets.QLineEdit(self.frame_11)
        self.AnalysisOutEntry.setObjectName("AnalysisOutEntry")
        self.horizontalLayout_6.addWidget(self.AnalysisOutEntry)
        self.AnalysisOutFindButton = QtWidgets.QPushButton(self.frame_11)
        self.AnalysisOutFindButton.setObjectName("AnalysisOutFindButton")
        self.horizontalLayout_6.addWidget(self.AnalysisOutFindButton)
        self.verticalLayout_7.addWidget(self.frame_11)
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.AlignPreEntry = QtWidgets.QLineEdit(self.frame_8)
        self.AlignPreEntry.setObjectName("AlignPreEntry")
        self.verticalLayout_7.addWidget(self.AlignPreEntry)
        self.label_9 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.AlignCommandEntry = QtWidgets.QLineEdit(self.frame_8)
        self.AlignCommandEntry.setObjectName("AlignCommandEntry")
        self.verticalLayout_7.addWidget(self.AlignCommandEntry)
        self.label_13 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.AlignQualityEntry = QtWidgets.QLineEdit(self.frame_8)
        self.AlignQualityEntry.setObjectName("AlignQualityEntry")
        self.verticalLayout_7.addWidget(self.AlignQualityEntry)
        self.line = QtWidgets.QFrame(self.frame_8)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.AnalysisStatusLab = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setItalic(True)
        self.AnalysisStatusLab.setFont(font)
        self.AnalysisStatusLab.setObjectName("AnalysisStatusLab")
        self.verticalLayout_7.addWidget(self.AnalysisStatusLab)
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.CheckButton = QtWidgets.QPushButton(self.frame_12)
        self.CheckButton.setObjectName("CheckButton")
        self.horizontalLayout_7.addWidget(self.CheckButton)
        self.AnalyseButton = QtWidgets.QPushButton(self.frame_12)
        self.AnalyseButton.setObjectName("AnalyseButton")
        self.horizontalLayout_7.addWidget(self.AnalyseButton)
        self.verticalLayout_7.addWidget(self.frame_12)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.Analysis)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5.addWidget(self.frame_6)
        self.tabWidget.addTab(self.Analysis, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.DBNameLab = QtWidgets.QLabel(self.frame)
        self.DBNameLab.setObjectName("DBNameLab")
        self.horizontalLayout.addWidget(self.DBNameLab)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 787, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect_to_database = QtWidgets.QAction(MainWindow)
        self.actionConnect_to_database.setObjectName("actionConnect_to_database")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionConnect_to_database)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FUR"))
        self.label_3.setText(_translate("MainWindow", "Database information"))
        self.label_19.setText(_translate("MainWindow", "Settings used:"))
        self.numAnnoLab.setText(_translate("MainWindow", "Number of annotations: <annonum>"))
        self.RegionConfigLab.setText(_translate("MainWindow", "Flanking region settings: <offset>bp offset and <size>bp size."))
        self.DedupConfigLab.setText(_translate("MainWindow", "Deduplication settings: <mincontig>bp minimum contig size."))
        self.label_5.setText(_translate("MainWindow", "Table sizes:"))
        self.FlankingTabLab.setText(_translate("MainWindow", "Flanking table (unduplicated) contains <entries> entries totalling <basepair> basepairs."))
        self.UnmaskTabLab.setText(_translate("MainWindow", "Unmasked table (pre identitied repeats removed) contains <entries> entries totalling <basepair> basepairs."))
        self.DedupTabLab.setText(_translate("MainWindow", "Deduplicated table (above plus BLAT matches removed) contains <entries> entries totalling <basepair> basepairs."))
        self.CalcQualButton.setText(_translate("MainWindow", "Calculate database quality"))
        self.label_6.setText(_translate("MainWindow", "Database quality:"))
        self.OverlappingLab.setText(_translate("MainWindow", "The database contains <overlapRegions> overlapping regions. Affecting <overlapAnno> annotations."))
        self.label_14.setText(_translate("MainWindow", "Unique regions are:"))
        self.totalAnnoSenseLab.setText(_translate("MainWindow", "- missing from the sense end of <senseNull> annotations."))
        self.totalAnnoAntiLab.setText(_translate("MainWindow", "- missing from the antisense end of <antiNull> annotations."))
        self.totalAnnoAbsentLab.setText(_translate("MainWindow", "- absent from <bothNull> annotations."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Info), _translate("MainWindow", "Info"))
        self.label_12.setText(_translate("MainWindow", "Find:"))
        self.label_11.setText(_translate("MainWindow", "ID:"))
        self.annoButton.setText(_translate("MainWindow", "Annotation"))
        self.contigButton.setText(_translate("MainWindow", "Contig"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Inspect), _translate("MainWindow", "Inspect"))
        self.label_2.setText(_translate("MainWindow", "Region Settings"))
        self.groupBox.setTitle(_translate("MainWindow", "Orientation"))
        self.GenomicRB.setText(_translate("MainWindow", "Genomic"))
        self.OriSenseRB.setText(_translate("MainWindow", "Sense"))
        self.OriAntiRB.setText(_translate("MainWindow", "Antisense"))
        self.OriBiRB.setText(_translate("MainWindow", "Bidirectional"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Ends"))
        self.EndSenseRB.setText(_translate("MainWindow", "Sense"))
        self.EndAntiRB.setText(_translate("MainWindow", "AntiSense"))
        self.EndBothRB.setText(_translate("MainWindow", "Both"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Size"))
        self.SizeAllRB.setText(_translate("MainWindow", "All (excepting equal option)"))
        self.SizeLargestRB.setText(_translate("MainWindow", "Largest"))
        self.SizeClosestRB.setText(_translate("MainWindow", "Closest"))
        self.SizeFixedRB.setText(_translate("MainWindow", "Fixed size (bp)"))
        self.SizeEqualBox.setText(_translate("MainWindow", "Equal sense/antisense lengths"))
        self.label_7.setText(_translate("MainWindow", "Alignment Settings"))
        self.label_8.setText(_translate("MainWindow", "Transcriptome file:"))
        self.RecursiveBox.setText(_translate("MainWindow", "Recursive (enter folder paths below)"))
        self.TransButton.setText(_translate("MainWindow", "Find"))
        self.label_10.setText(_translate("MainWindow", "Analysis output file:"))
        self.AnalysisOutFindButton.setText(_translate("MainWindow", "Find"))
        self.label_4.setText(_translate("MainWindow", "Alignment setup command:"))
        self.AlignPreEntry.setText(_translate("MainWindow", "bowtie2-build <seqfile> Contigs"))
        self.label_9.setText(_translate("MainWindow", "Alignment command:"))
        self.AlignCommandEntry.setText(_translate("MainWindow", "bowtie2 --threads 2 -x Contigs -U <transcriptfile> \"<samfile>\""))
        self.label_13.setText(_translate("MainWindow", "Quality:"))
        self.AlignQualityEntry.setText(_translate("MainWindow", "40"))
        self.AnalysisStatusLab.setText(_translate("MainWindow", "Waiting on user input"))
        self.CheckButton.setText(_translate("MainWindow", "Check settings"))
        self.AnalyseButton.setText(_translate("MainWindow", "Start analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Analysis), _translate("MainWindow", "Analysis"))
        self.label.setText(_translate("MainWindow", "Connected to database: "))
        self.DBNameLab.setText(_translate("MainWindow", "Disconnected"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionConnect_to_database.setText(_translate("MainWindow", "Connect to database"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
