# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetupDB.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigureDB(object):
    def setupUi(self, ConfigureDB):
        ConfigureDB.setObjectName("ConfigureDB")
        ConfigureDB.resize(464, 682)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigureDB)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleBar = QtWidgets.QFrame(ConfigureDB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleBar.sizePolicy().hasHeightForWidth())
        self.TitleBar.setSizePolicy(sizePolicy)
        self.TitleBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TitleBar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TitleBar.setObjectName("TitleBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.TitleBar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.MainHeader = QtWidgets.QLabel(self.TitleBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.MainHeader.setFont(font)
        self.MainHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.MainHeader.setObjectName("MainHeader")
        self.horizontalLayout_2.addWidget(self.MainHeader)
        self.verticalLayout.addWidget(self.TitleBar)
        self.frame_3 = QtWidgets.QFrame(ConfigureDB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.loadButton = QtWidgets.QPushButton(self.frame_3)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_5.addWidget(self.loadButton)
        self.saveButton = QtWidgets.QPushButton(self.frame_3)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_5.addWidget(self.saveButton)
        self.verticalLayout.addWidget(self.frame_3)
        self.OptionBar = QtWidgets.QFrame(ConfigureDB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OptionBar.sizePolicy().hasHeightForWidth())
        self.OptionBar.setSizePolicy(sizePolicy)
        self.OptionBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OptionBar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.OptionBar.setObjectName("OptionBar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OptionBar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.OptionBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.OptionBar)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AnnoFileEntry = QtWidgets.QLineEdit(self.frame)
        self.AnnoFileEntry.setObjectName("AnnoFileEntry")
        self.horizontalLayout.addWidget(self.AnnoFileEntry)
        self.AnnoFileButton = QtWidgets.QPushButton(self.frame)
        self.AnnoFileButton.setObjectName("AnnoFileButton")
        self.horizontalLayout.addWidget(self.AnnoFileButton)
        self.verticalLayout_2.addWidget(self.frame)
        self.label_2 = QtWidgets.QLabel(self.OptionBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.frame_2 = QtWidgets.QFrame(self.OptionBar)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.GenomeFileEntry = QtWidgets.QLineEdit(self.frame_2)
        self.GenomeFileEntry.setObjectName("GenomeFileEntry")
        self.horizontalLayout_6.addWidget(self.GenomeFileEntry)
        self.GenomeFileButton = QtWidgets.QPushButton(self.frame_2)
        self.GenomeFileButton.setObjectName("GenomeFileButton")
        self.horizontalLayout_6.addWidget(self.GenomeFileButton)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.label_3 = QtWidgets.QLabel(self.OptionBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.frame_4 = QtWidgets.QFrame(self.OptionBar)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.FlankingSizeLab = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.FlankingSizeLab.setFont(font)
        self.FlankingSizeLab.setObjectName("FlankingSizeLab")
        self.horizontalLayout_3.addWidget(self.FlankingSizeLab)
        self.FlankingSizeEntry = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FlankingSizeEntry.sizePolicy().hasHeightForWidth())
        self.FlankingSizeEntry.setSizePolicy(sizePolicy)
        self.FlankingSizeEntry.setObjectName("FlankingSizeEntry")
        self.horizontalLayout_3.addWidget(self.FlankingSizeEntry)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.OptionBar)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.FlankingOffsetEntry = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FlankingOffsetEntry.sizePolicy().hasHeightForWidth())
        self.FlankingOffsetEntry.setSizePolicy(sizePolicy)
        self.FlankingOffsetEntry.setObjectName("FlankingOffsetEntry")
        self.horizontalLayout_7.addWidget(self.FlankingOffsetEntry)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.label_6 = QtWidgets.QLabel(self.OptionBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.OptionBar)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.frame_7 = QtWidgets.QFrame(self.OptionBar)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.BLATInstYesRB = QtWidgets.QRadioButton(self.frame_7)
        self.BLATInstYesRB.setChecked(True)
        self.BLATInstYesRB.setObjectName("BLATInstYesRB")
        self.horizontalLayout_9.addWidget(self.BLATInstYesRB)
        self.BLATInstNoRB = QtWidgets.QRadioButton(self.frame_7)
        self.BLATInstNoRB.setObjectName("BLATInstNoRB")
        self.horizontalLayout_9.addWidget(self.BLATInstNoRB)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.OptionBar)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.BLATEntry = QtWidgets.QLineEdit(self.frame_6)
        self.BLATEntry.setEnabled(False)
        self.BLATEntry.setObjectName("BLATEntry")
        self.horizontalLayout_8.addWidget(self.BLATEntry)
        self.BLATFileButton = QtWidgets.QPushButton(self.frame_6)
        self.BLATFileButton.setObjectName("BLATFileButton")
        self.horizontalLayout_8.addWidget(self.BLATFileButton)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.groupBox = QtWidgets.QGroupBox(self.OptionBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.DedupLocalRB = QtWidgets.QRadioButton(self.groupBox)
        self.DedupLocalRB.setChecked(True)
        self.DedupLocalRB.setObjectName("DedupLocalRB")
        self.verticalLayout_4.addWidget(self.DedupLocalRB)
        self.DedupGenomeRB = QtWidgets.QRadioButton(self.groupBox)
        self.DedupGenomeRB.setObjectName("DedupGenomeRB")
        self.verticalLayout_4.addWidget(self.DedupGenomeRB)
        self.DedupBothRB = QtWidgets.QRadioButton(self.groupBox)
        self.DedupBothRB.setObjectName("DedupBothRB")
        self.verticalLayout_4.addWidget(self.DedupBothRB)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame_9 = QtWidgets.QFrame(self.OptionBar)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.frame_9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.MinContigSizeEntry = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MinContigSizeEntry.sizePolicy().hasHeightForWidth())
        self.MinContigSizeEntry.setSizePolicy(sizePolicy)
        self.MinContigSizeEntry.setObjectName("MinContigSizeEntry")
        self.horizontalLayout_10.addWidget(self.MinContigSizeEntry)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.label_9 = QtWidgets.QLabel(self.OptionBar)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.line = QtWidgets.QFrame(self.OptionBar)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.ConnectionStatus = QtWidgets.QLabel(self.OptionBar)
        font = QtGui.QFont()
        font.setItalic(True)
        self.ConnectionStatus.setFont(font)
        self.ConnectionStatus.setObjectName("ConnectionStatus")
        self.verticalLayout_2.addWidget(self.ConnectionStatus)
        self.verticalLayout.addWidget(self.OptionBar)
        self.Buttons = QtWidgets.QFrame(ConfigureDB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Buttons.sizePolicy().hasHeightForWidth())
        self.Buttons.setSizePolicy(sizePolicy)
        self.Buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Buttons.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Buttons.setObjectName("Buttons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Buttons)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.backButton = QtWidgets.QPushButton(self.Buttons)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_4.addWidget(self.backButton)
        self.createButton = QtWidgets.QPushButton(self.Buttons)
        self.createButton.setObjectName("createButton")
        self.horizontalLayout_4.addWidget(self.createButton)
        self.verticalLayout.addWidget(self.Buttons)

        self.retranslateUi(ConfigureDB)
        QtCore.QMetaObject.connectSlotsByName(ConfigureDB)

    def retranslateUi(self, ConfigureDB):
        _translate = QtCore.QCoreApplication.translate
        ConfigureDB.setWindowTitle(_translate("ConfigureDB", "FUR - Configure database"))
        self.MainHeader.setText(_translate("ConfigureDB", "Configure FUR database"))
        self.loadButton.setText(_translate("ConfigureDB", "Load Config"))
        self.saveButton.setText(_translate("ConfigureDB", "Save Config"))
        self.label.setText(_translate("ConfigureDB", "Annotation file:"))
        self.AnnoFileButton.setText(_translate("ConfigureDB", "Find"))
        self.label_2.setText(_translate("ConfigureDB", "Genome file:"))
        self.GenomeFileButton.setText(_translate("ConfigureDB", "Find"))
        self.label_3.setText(_translate("ConfigureDB", "Flanking Region location"))
        self.FlankingSizeLab.setText(_translate("ConfigureDB", "Size: "))
        self.FlankingSizeEntry.setText(_translate("ConfigureDB", "5000"))
        self.label_5.setText(_translate("ConfigureDB", "Offset:"))
        self.FlankingOffsetEntry.setText(_translate("ConfigureDB", "0"))
        self.label_6.setText(_translate("ConfigureDB", "Deduplication"))
        self.label_7.setText(_translate("ConfigureDB", "BLAT installed and within file path:"))
        self.BLATInstYesRB.setText(_translate("ConfigureDB", "Yes"))
        self.BLATInstNoRB.setText(_translate("ConfigureDB", "No"))
        self.BLATFileButton.setText(_translate("ConfigureDB", "Find"))
        self.groupBox.setTitle(_translate("ConfigureDB", "Deduplication method:"))
        self.DedupLocalRB.setText(_translate("ConfigureDB", "Compare flanking regions (fastest)"))
        self.DedupGenomeRB.setText(_translate("ConfigureDB", "Compare flanking regions to genome"))
        self.DedupBothRB.setText(_translate("ConfigureDB", "Compare flanking regions and compare to genome (slowest)"))
        self.label_10.setText(_translate("ConfigureDB", "Minimum contig size:"))
        self.MinContigSizeEntry.setText(_translate("ConfigureDB", "20"))
        self.label_9.setText(_translate("ConfigureDB", "See documentation for advanced settings available from the terminal."))
        self.ConnectionStatus.setText(_translate("ConfigureDB", "Waiting user input"))
        self.backButton.setText(_translate("ConfigureDB", "Back"))
        self.createButton.setText(_translate("ConfigureDB", "Configure database"))
