# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startscreen.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Connect(object):
    def setupUi(self, Connect):
        Connect.setObjectName("Connect")
        Connect.resize(408, 401)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Connect.sizePolicy().hasHeightForWidth())
        Connect.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Connect)
        self.verticalLayout.setContentsMargins(9, 9, 9, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleBar = QtWidgets.QFrame(Connect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleBar.sizePolicy().hasHeightForWidth())
        self.TitleBar.setSizePolicy(sizePolicy)
        self.TitleBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TitleBar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TitleBar.setObjectName("TitleBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.TitleBar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.WelcomeText = QtWidgets.QLabel(self.TitleBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.WelcomeText.setFont(font)
        self.WelcomeText.setAlignment(QtCore.Qt.AlignCenter)
        self.WelcomeText.setObjectName("WelcomeText")
        self.horizontalLayout_2.addWidget(self.WelcomeText)
        self.verticalLayout.addWidget(self.TitleBar)
        self.OptionBar = QtWidgets.QFrame(Connect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OptionBar.sizePolicy().hasHeightForWidth())
        self.OptionBar.setSizePolicy(sizePolicy)
        self.OptionBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OptionBar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.OptionBar.setObjectName("OptionBar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OptionBar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DatabaseName = QtWidgets.QLabel(self.OptionBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DatabaseName.setFont(font)
        self.DatabaseName.setObjectName("DatabaseName")
        self.verticalLayout_2.addWidget(self.DatabaseName)
        self.DatabaseNameEntry = QtWidgets.QLineEdit(self.OptionBar)
        self.DatabaseNameEntry.setObjectName("DatabaseNameEntry")
        self.verticalLayout_2.addWidget(self.DatabaseNameEntry)
        self.groupBox = QtWidgets.QGroupBox(self.OptionBar)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.UseSQLiteradio = QtWidgets.QRadioButton(self.groupBox)
        self.UseSQLiteradio.setChecked(True)
        self.UseSQLiteradio.setObjectName("UseSQLiteradio")
        self.horizontalLayout_3.addWidget(self.UseSQLiteradio)
        self.UseSQLradio = QtWidgets.QRadioButton(self.groupBox)
        self.UseSQLradio.setObjectName("UseSQLradio")
        self.horizontalLayout_3.addWidget(self.UseSQLradio)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.SQLServer = QtWidgets.QLabel(self.OptionBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SQLServer.setFont(font)
        self.SQLServer.setObjectName("SQLServer")
        self.verticalLayout_2.addWidget(self.SQLServer)
        self.SQLServerEntry = QtWidgets.QLineEdit(self.OptionBar)
        self.SQLServerEntry.setEnabled(False)
        self.SQLServerEntry.setObjectName("SQLServerEntry")
        self.verticalLayout_2.addWidget(self.SQLServerEntry)
        self.SQLUsername = QtWidgets.QLabel(self.OptionBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SQLUsername.setFont(font)
        self.SQLUsername.setObjectName("SQLUsername")
        self.verticalLayout_2.addWidget(self.SQLUsername)
        self.SQLUsernameEntry = QtWidgets.QLineEdit(self.OptionBar)
        self.SQLUsernameEntry.setEnabled(False)
        self.SQLUsernameEntry.setObjectName("SQLUsernameEntry")
        self.verticalLayout_2.addWidget(self.SQLUsernameEntry)
        self.SQLPassword = QtWidgets.QLabel(self.OptionBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SQLPassword.setFont(font)
        self.SQLPassword.setObjectName("SQLPassword")
        self.verticalLayout_2.addWidget(self.SQLPassword)
        self.SQLPasswordEntry = QtWidgets.QLineEdit(self.OptionBar)
        self.SQLPasswordEntry.setEnabled(False)
        self.SQLPasswordEntry.setObjectName("SQLPasswordEntry")
        self.verticalLayout_2.addWidget(self.SQLPasswordEntry)
        self.Buttons = QtWidgets.QFrame(self.OptionBar)
        self.Buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Buttons.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Buttons.setObjectName("Buttons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Buttons)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LoadButton = QtWidgets.QPushButton(self.Buttons)
        self.LoadButton.setObjectName("LoadButton")
        self.horizontalLayout_4.addWidget(self.LoadButton)
        self.CreateButton = QtWidgets.QPushButton(self.Buttons)
        self.CreateButton.setObjectName("CreateButton")
        self.horizontalLayout_4.addWidget(self.CreateButton)
        self.verticalLayout_2.addWidget(self.Buttons)
        self.ConnectionStatus = QtWidgets.QLabel(self.OptionBar)
        self.ConnectionStatus.setText("")
        self.ConnectionStatus.setObjectName("ConnectionStatus")
        self.verticalLayout_2.addWidget(self.ConnectionStatus)
        self.verticalLayout.addWidget(self.OptionBar)
        self.AboutBar = QtWidgets.QFrame(Connect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AboutBar.sizePolicy().hasHeightForWidth())
        self.AboutBar.setSizePolicy(sizePolicy)
        self.AboutBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AboutBar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.AboutBar.setObjectName("AboutBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.AboutBar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.AboutBar)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.AboutBar)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.AboutBar)

        self.retranslateUi(Connect)
        QtCore.QMetaObject.connectSlotsByName(Connect)

    def retranslateUi(self, Connect):
        _translate = QtCore.QCoreApplication.translate
        Connect.setWindowTitle(_translate("Connect", "FUR - Connect to database"))
        self.WelcomeText.setText(_translate("Connect", "Flanking Unique Region Database (FURdb)"))
        self.DatabaseName.setText(_translate("Connect", "Database name:"))
        self.DatabaseNameEntry.setText(_translate("Connect", "FURdb"))
        self.groupBox.setTitle(_translate("Connect", "Database type:"))
        self.UseSQLiteradio.setText(_translate("Connect", "Database file (SQLite)"))
        self.UseSQLradio.setText(_translate("Connect", "Database server (SQL)"))
        self.SQLServer.setText(_translate("Connect", "SQL Server:"))
        self.SQLUsername.setText(_translate("Connect", "SQL Username:"))
        self.SQLPassword.setText(_translate("Connect", "SQL Password:"))
        self.LoadButton.setText(_translate("Connect", "Load database"))
        self.CreateButton.setText(_translate("Connect", "Create database"))
        self.label.setText(_translate("Connect", "FUR Version 0.8"))
        self.label_2.setText(_translate("Connect", "UI Version 0.1"))
